name: universal_video_controls

packages:
  - ./**
# dart pub global activate melos

scripts:
  analyze:
    exec: dart analyze .
  pub_get:
    run: melos exec -- flutter pub get
  format:
    run: melos exec -- dart format . && dart fix --apply .
  upgrade_major_versions:
    run: |
      melos exec -- flutter pub upgrade --major-versions
  publish:
    run: |
      melos publish --no-dry-run -y
